# Generated by Django 4.0.4 on 2022-05-23 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('gn', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('max_weight', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistic_service.city')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('phone_number', models.BigIntegerField()),
                ('state', models.CharField(max_length=45)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistic_service.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logistician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_model', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_waybill', models.IntegerField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('state', models.CharField(max_length=45)),
                ('distinct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistic_service.district')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistic_service.driver')),
                ('logistician', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistic_service.logistician')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistic_service.district')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('state', models.CharField(blank=True, max_length=45)),
                ('date', models.DateField(auto_now_add=True)),
                ('mass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.BigIntegerField()),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistic_service.manufacturer_model'),
        ),
    ]
