# Generated by Django 4.0.4 on 2022-04-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='logistician',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='street',
            name='district',
        ),
        migrations.RemoveField(
            model_name='waybill',
            name='distinct',
        ),
        migrations.RemoveField(
            model_name='waybill',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='waybill',
            name='logistician',
        ),
        migrations.RemoveField(
            model_name='waybill',
            name='order',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Logistician',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
        migrations.DeleteModel(
            name='Waybill',
        ),
    ]
