# Generated by Django 4.0.4 on 2022-05-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_service', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_model', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Orders_Waybills_State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistic_service.manufacturer_model'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logistic_service.driver_states'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic_service.orders_waybills_state'),
        ),
    ]
