# Generated by Django 4.0.4 on 2022-05-08 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic_service', '0004_driver_states_manufacturer_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('phone_number', models.BigIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('organization', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=120)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logistic_service.orderer'),
            preserve_default=False,
        ),
    ]
