# Generated by Django 4.0.4 on 2022-05-16 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistic_service', '0005_remove_order_address_remove_order_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderer',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='waybill',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='state',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='state',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='Driver_States',
        ),
        migrations.DeleteModel(
            name='Orderer',
        ),
        migrations.DeleteModel(
            name='Orders_Waybills_State',
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='logistic_service.city'),
            preserve_default=False,
        ),
    ]
