# Generated by Django 4.0.4 on 2022-05-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_service', '0006_city_remove_orderer_userid_remove_order_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.BigIntegerField(default=9000000000),
            preserve_default=False,
        ),
    ]
