# Generated by Django 4.0.4 on 2022-05-16 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_service', '0007_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logistic_service.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logistic_service.district'),
            preserve_default=False,
        ),
    ]
