# Generated by Django 4.0.4 on 2022-05-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_service', '0008_order_city_order_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
    ]
